"""Add password to Users

Revision ID: f623e417c96e
Revises: 
Create Date: 2022-09-08 11:59:04.300973

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f623e417c96e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
